#!/bin/bash

#
# Called from yadm on updating $HOME folder with the dotfiles.
#
# Install (if ssh keys are not set):
#    yadm clone https://github.com/dvp2015/dotfiles-1.git
#

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Run YADM bootstrap"

# yadm decrypt
# yadm perms
yadm remote set-url origin  git@github.com:dvp2015/dotfiles-1.git

echo "Init submodules"
yadm submodule init
yadm submodule update --recursive --init


if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi




