#!/usr/bin/env bash

function install_nerd_fonts() {
    # https://github.com/ryanoasis/nerd-fonts
    echo "Installing nerd fonts"
    git clone https://github.com/ryanoasis/nerd-fonts .yadm/fonts --depth=1
    cd .yadm/fonts
    ./install.sh
    cd ..
    rm -rf fonts
    cd "$HOME"
}

install_nerd_fonts && fc-cache -vf ~/.local/share/fonts/

