[python]
# customize python binary path for pixi
python_binary = [
  # this is the python from PATH if in a pixi shell
  # (assuming you don't have python on your global PATH)
  "python",
  # fall back to pixi's python if it's available
  ".pixi/envs/default/bin/python",
]

# [pixi]
# symbol = "📦 "

# [cmake]
# disabled = false

# [direnv]
# disabled = true
