#!/bin/bash

#
# Called from yadm on updating $HOME folder with the dotfiles.
#
# Install (if ssh keys are not set):
#    yadm clone https://github.com/dvp2015/dotfiles-1.git
#

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Run YADM bootstrap"

# yadm decrypt
# yadm perms
yadm remote set-url origin  git@github.com:dvp2015/dotfiles-1.git

echo "Init submodules"
yadm submodule init
yadm submodule update --recursive --init

echo "Installing powerline fonts"
# https://powerline.readthedocs.io/en/latest/installation/linux.html#fonts-installation
pip install powerline-status
git clone https://github.com/powerline/fonts.git .yadm/fonts --depth=1
cd .yadm/fonts

./install.sh

wget https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
wget https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf
mv PowerlineSymbols.otf ~/.local/share/fonts/
mv 10-powerline-symbols.conf ~/.config/fontconfig/conf.d/
fc-cache -vf ~/.local/share/fonts/

cd ..
rm -rf fonts
cd "$HOME"

if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi


if [[ -d "$HOME/.yadm/installable/bats" ]]; then
    echo "Installing bats (bash script testing framework)"
    pushd "$HOME/.yadm/installable/bats" >/dev/null 2>&1
    ./install.sh "$HOME/.local"
    popd >/dev/null 2>&1
else
    echo "Cannot find bats"
fi


if [[ -d "$HOME/.yadm/installable/diff-so-fancy" ]]; then
    echo "Installing diff-so-fancy (git diff human readable)"
    cp "$HOME/.yadm/installable/diff-so-fancy/diff-so-fancy" "$HOME/.local/bin"
    cp -r "$HOME/.yadm/installable/diff-so-fancy/lib" "$HOME/.local/bin"
else
    echo "Cannot find diff-so-fancy"
fi


